mrsProject/Models/Order.cs
using mrsProject.Utilities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace mrsProject.Models
{
    public class Order
    {
        public Int32 OrderID { get; set; }

        [Display(Name = "Order Number")]
        public Int32 OrderNumber { get; set; }

        [Display(Name = "Order Date")]
        public DateTime OrderDate { get; set; }

        [Display(Name = "Order Subtotal")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Decimal OrderSubtotal
        {
            get { return OrderDetails.Sum(od => od.OrderExtendedPrice); }
            set{ }
        }

        [Display(Name = "Order Total")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Decimal OrderTotal
        {
            get { return OrderSubtotal + ShippingCost; }
        }
        public Decimal ShippingCostFirstBook = 3.50m;

        public Decimal ShippingCostNextBook = 1.50m;
       
        public Int32 TotalQuantityBooks
        {
            get { return OrderDetails.Sum(od => od.OrderQuantity); }
        }
        [Display(Name = "Shipping Cost")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Decimal ShippingCost
        {
            get
            {
                if (TotalQuantityBooks == 1)
                {
                    return ShippingCost = ShippingCostFirstBook;
                }
                else
                {
                    return ShippingCost = ShippingCostFirstBook + ShippingCostNextBook * (TotalQuantityBooks - 1);
                }
            }
            set { }
        }

        [Display(Name = "Order Notes")]
        public String OrderNotes { get; set; }

        [Display(Name = "Payment Method")]
        public String PaymentMethod { get; set; }

        [Display(Name = "Pending Order")]
        public Boolean PendingOrder { get; set; }

        public AppUser user { get; set; }

        public List<OrderDetail> OrderDetails { get; set; }

        public Order()
        {
            if (OrderDetails == null)
            {
                OrderDetails = new List<OrderDetail>();
            }

            OrderDate = System.DateTime.Today;
            
        }
    }
}

mrsProject/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mrsProject.DAL;
using mrsProject.Models;
using mrsProject.Utilities;

namespace mrsProject.Controllers
{
    public class OrdersController : Controller
    {
        private readonly AppDbContext _context;

        public OrdersController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            List<Order> Orders = new List<Order>();
            if (User.IsInRole("Customer"))
            {
                Orders = _context.Orders.Where(o => o.user.UserName == User.Identity.Name).ToList();
            }
            else
            {
                Orders = _context.Orders.Include(o => o.OrderDetails).ToList();
            }
            return View(Orders);
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.Include(r => r.OrderDetails).ThenInclude(r => r.Book).FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderID,OrderNumber,OrderDate,OrderNotes")] Order order)
        {

            
            order.OrderDate = System.DateTime.Today;

            if (ModelState.IsValid)
            {

                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction("AddToOrder", new { id = order.OrderID });
            }
            return View(order);
        }

        public IActionResult AddToOrder(int? id)
        {
            if (id == null)
            {
                return View("Error", new string[] { "You must specify a product to add!" });
            }

            List<Order> Orders = new List<Order>();

            Orders = _context.Orders.Where(o => o.user.UserName == User.Identity.Name).ToList();

            Order cart = Orders.FirstOrDefault(o => o.PendingOrder == true);

            if (cart == null)
            {
                cart = new Order();
                cart.PendingOrder = true;
                String userid = User.Identity.Name;
                AppUser user = _context.Users.FirstOrDefault(u => u.UserName == userid);
                cart.user = user;
            }

            Order ord = cart;
 
            if (ord == null)
            {
                return View("Error", new string[] { "Order not found!" });
            }

            List<Book> Books = new List<Book>();

            Books = _context.Books.Where(b => b.BookID == id).ToList();

            Book book = Books.FirstOrDefault(b => b.BookID == id);

            OrderDetail rd = new OrderDetail
            {
                Order = ord,
                Book = book
            };

            //ViewBag.AllProducts = GetAllProducts(id);
            return View("AddToOrder", rd);
        }

        [HttpPost]
        public IActionResult AddToOrder(OrderDetail rd)
        {


            //find the course associated with the selected course id
            Book book = _context.Books.Find(rd.Book.BookID);

            //set the registration detail's course equal to the course we just found
            rd.Book = book;

            List<Order> Orders = new List<Order>();

            Orders = _context.Orders.Where(o => o.user.UserName == User.Identity.Name).ToList();

            Order cart = Orders.FirstOrDefault(o => o.PendingOrder == true);

            if (cart == null)
            {
                cart = new Order();
                cart.PendingOrder = true;
                cart.OrderNumber = GenerateNextOrderNumber.GetNextOrderNumber(_context);
                String userid = User.Identity.Name;
                AppUser user = _context.Users.FirstOrDefault(u => u.UserName == userid);
                cart.user = user;

                _context.Orders.Add(cart);
                _context.SaveChanges();
            }

            //find the registration based on the id
            //Order ord = _context.Orders.Find(rd.Order.OrderID); 

            //set the registration detail's registration equal to the registration we just found
            rd.Order = cart;

            //set the course fee for this detail equal to the current course fee
            rd.OrderDetailPrice = rd.Book.Price;

            //add total fees
            rd.OrderExtendedPrice = rd.OrderQuantity * rd.OrderDetailPrice;

            if (ModelState.IsValid)
            {
                _context.OrderDetails.Add(rd);
                _context.SaveChanges();
                return RedirectToAction("Details", new { id = rd.Order.OrderID });
            }
            
            return View(rd);
        }




        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Order order)
        {
            //Find the related registration in the database
            Order DbOd = _context.Orders.Find(order.OrderID);

            //Update the notes
            DbOd.OrderNotes = order.OrderNotes;

            //Update the database
            _context.Orders.Update(DbOd);

            //Save changes
            _context.SaveChanges();

            //Go back to index
            return RedirectToAction(nameof(Index));
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult RemoveFromOrder(int? id)
        {
            if (id == null)
            {
                return View("Error", new string[] { "You need to specify an order id" });
            }

            Order od = _context.Orders.Include(r => r.OrderDetails).ThenInclude(r => r.Book).FirstOrDefault(r => r.OrderID == id);

            if (od == null || od.OrderDetails.Count == 0)
            {
                return RedirectToAction("Details", new { id = id });
            }

            //pass the list of order details to the view
            return View(od.OrderDetails);
        }


        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.OrderID == id);
        }

        //GET
        public IActionResult CheckOut(int? id)
        {
            if (id == null)
            {
                return View("Error", new string[] { "You need to specify an order id" });
            }

            Order cart = _context.Orders.Include(o => o.OrderDetails).Include(o => o.user).FirstOrDefault(o => o.OrderID == id);

            //Order cart = _context.Orders.Include(r => r.OrderDetails).ThenInclude(r => r.Book).FirstOrDefault(r => r.OrderID == id);

            if (cart == null)
            {
                return View("Error");
            }


            return View("CheckOut", cart);
        }

        [HttpPost]
        public IActionResult CheckOut(Order cart, string SelectedCoupon, int SelectedCreditCard)
        {
            String userid = User.Identity.Name;
            AppUser CurrentUser = _context.Users.FirstOrDefault(u => u.UserName == userid);

            List<Order> Orders = new List<Order>();

            Orders = _context.Orders.Include(o => o.OrderDetails).Include(o => o.user).Where(o => o.user.UserName == CurrentUser.UserName).ToList();

            Order dbCheckOutOrder = Orders.FirstOrDefault(o => o.PendingOrder == true);


            //Order dbCheckOutOrder = _context.Orders.Include(o => o.OrderDetails).Include(o => o.user).FirstOrDefault(o => o.PendingOrder == true);



            if (SelectedCreditCard == 0)
            {
                dbCheckOutOrder.PaymentMethod = CurrentUser.CreditCard1;
            }
            else if (SelectedCreditCard == 1)
            {
                dbCheckOutOrder.PaymentMethod = CurrentUser.CreditCard2;
            }
            else if (SelectedCreditCard == 2)
            {
                dbCheckOutOrder.PaymentMethod = CurrentUser.CreditCard3;

mrsProject/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mrsProject.DAL;
using mrsProject.Models;

namespace mrsProject.Controllers
{
    public enum SortOptions { Title, Author, NumberPurchased, New, Old, Rated}
   
    public class SearchController : Controller

    {
        private AppDbContext _db;
        public IActionResult Index()
        {
            return View();
        }

       

        public ActionResult Search()
        {
            ViewBag.AllBooks = GetAllBooks();
            return View("SearchResults");
        }



        public ActionResult DisplaySearchResults(string SearchGenre, string SearchTitle, string SearchAuthor, SortOptions sort)
        {
            ViewBag.BookCount = "The total number of books is" + _db.Books.Count();
            List<Book> SelectedBooks = new List<Book>();
            

            var query = from r in _db.Books
                        select r;
            if (SearchGenre != null && SearchGenre != "")
            {
                query = query.Where(r => r.Genre.GenreName.Contains(SearchGenre));
            }
            if (SearchTitle != null && SearchTitle != "")
            {
                query = query.Where(r => r.Title.Contains(SearchTitle));
            }
            if (SearchAuthor != null && SearchAuthor != "")
            {
                query = query.Where(r => r.Author.Contains(SearchAuthor));
            }

            SelectedBooks = query.Include(r => r.Genre).ToList();
            ViewBag.TotalBooks = _db.Books.Count();
            ViewBag.SelectedBooks = SelectedBooks.Count();


            


            switch (sort)
            {
                case SortOptions.Title:
                    return View("SearchResults", SelectedBooks.OrderBy(r => r.Title));
                case SortOptions.Author:
                    return View("SearchResults", SelectedBooks.OrderBy(r => r.Author));
                case SortOptions.New:
                    return View("SearchResults", SelectedBooks.OrderBy(r => r.PublicationDate));
                case SortOptions.Old:
                    return View("SearchResults", SelectedBooks.OrderByDescending(r => r.PublicationDate));
                case SortOptions.NumberPurchased:
                    return View("SearchResults", SelectedBooks.OrderBy(r => r.NumPurchased));
                case SortOptions.Rated:
                    return View("SearchResults", SelectedBooks.OrderBy(r => r.SimpleRating));
            }
            

            return View();


        }

        public IActionResult BookDetails(int? id)
        {
            if (id == null) //Repo id not specified
            {
                return View("Error", new String[] { "Book ID not specified - which book do you want to view?" });
            }

            Book b = _db.Books.Include(r => r.Genre).FirstOrDefault(r => r.BookID == id);

            if (b == null) //Repo does not exist in database
            {
                return View("Error", new String[] { "Book not found in database" });
            }

            //if code gets this far, all is well
            return View(b);
        }

       
        public SearchController(AppDbContext context)
        {
            _db = context;
        }

        public SelectList GetAllBooks()
        {
            List<Book> Books = _db.Books.ToList();

            Book SelectNoBook = new Book() { BookID = 0, Title = "All Books" };

            Books.Add(SelectNoBook);

            SelectList AllBooks = new SelectList(Books.OrderBy(B => B.BookID), "BookID", "Title");

            return AllBooks;
        }

        public ActionResult AllBooks(string SearchString)
        {
            ViewBag.BookCount = "The total number of Books is " + _db.Books.Count();
            List<Book> SelectedBooks = new List<Book>();

            

            var query = from r in _db.Books
                        select r;

            SelectedBooks = query.Include(r => r.Genre).ToList();

            ViewBag.TotalBooks = _db.Books.Count();
            ViewBag.SelectedBooks = SelectedBooks.Count();
            return View("SearchResults", SelectedBooks);

        }
    }
}

mrsProject/Views/Orders/AddToOrder.cshtml
@model mrsProject.Models.OrderDetail

@{
    ViewData["Title"] = "AddToOrder";
}

<h2>Add To Order</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Order.OrderID)
    @Html.HiddenFor(model => model.Book.BookID)
    <div class="form=group">
        @Html.LabelFor(model => model.OrderQuantity, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.EditorFor(model => model.OrderQuantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrderQuantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add Book to Cart" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

mrsProject/Views/Orders/Checkout.cshtml
@model mrsProject.Models.Order

@{
    ViewData["Title"] = "CheckOut";
}

<h2>Checkout</h2>

@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            <p>Please Select Your Payment Method (Choose One)</p>
            <div class="checkbox">
                <label>
                    <input type="checkbox" value="0" /> @Html.DisplayFor(model => model.user.CreditCard1)
                </label>
            </div>
            <div class="checkbox">
                <label>
                    <input type="checkbox" value="1" /> @Html.DisplayFor(model => model.user.CreditCard2)
                </label>
            </div>
            <div class="checkbox">
                <label>
                    <input type="checkbox" value="2" /> @Html.DisplayFor(model => model.user.CreditCard3)
                </label>
            </div>
        </div>

        <dl class="dl-horizontal">
            <dt>
                <a asp-controller="Account" asp-action="ManageAccount" class="btn btn-success">Enter A New Credit Card</a>
            </dt>
        </dl>

        <div class="form-group">
            <label>Coupon Code:</label>
            <input name="SelectedCoupon" class="form-control" />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Proceed to Order Summary" class="btn btn-default">
            </div>
        </div>
    </div>
}

mrsProject/Views/Orders/Details.cshtml
@model mrsProject.Models.Order
@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderSubtotal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderSubtotal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShippingCost)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShippingCost)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.OrderTotal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderTotal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderNotes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderNotes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PendingOrder)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PendingOrder)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Orders" asp-action="Edit" asp-route-id="@Model.OrderID">Edit</a> |
    <a asp-controller="Orders" asp-action="CheckOut" asp-route-id="@Model.OrderID">Check Out</a> |
    <a asp-controller="Search" asp-action="Index">Back to List</a>
</div>

mrsProject/Views/Orders/Edit.cshtml
@model mrsProject.Models.Order

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderID" />
            <div class="form-group">
                <label asp-for="OrderNumber" class="control-label"></label>
                <input asp-for="OrderNumber" class="form-control" />
                <span asp-validation-for="OrderNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippingCost" class="control-label"></label>
                <input asp-for="ShippingCost" class="form-control" />
                <span asp-validation-for="ShippingCost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderNotes" class="control-label"></label>
                <input asp-for="OrderNotes" class="form-control" />
                <span asp-validation-for="OrderNotes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentMethod" class="control-label"></label>
                <input asp-for="PaymentMethod" class="form-control" />
                <span asp-validation-for="PaymentMethod" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="PendingOrder" /> @Html.DisplayNameFor(model => model.PendingOrder)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

mrsProject/Views/Orders/Index.cshtml
@model IEnumerable<mrsProject.Models.Order>
@{
    ViewData["Title"] = "Index";
}



<h2>Orders</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrderNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDetails)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderSubtotal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderTotal)

            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShippingCost)

            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderTotal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentMethod)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDetails)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderSubtotal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShippingCost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderTotal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentMethod)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.OrderID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.OrderID">Details</a> |

            </td>
        </tr>
        }
    </tbody>
</table>

mrsProject/Views/Orders/OrderConfirmation.cshtml
@model  mrsProject.Models.Order
@{
    ViewData["Title"] = "OrderConfirmation";
}

<h2>Order Confirmation</h2>

<h3>Congradulations! Your order has been confirmed! </h3>
<hr />

<div>
    <h4>Books</h4>
    <table class="table table-sm table-hover table-striped">
        <thead>
            <tr>
                <th>Book Title</th>
                <th>Book Price</th>
                <th>Book Quantity</th>
                <th>Book Extended Price</th>
            </tr>
        </thead>
        <tbody>
            @foreach (mrsProject.Models.OrderDetail pd in Model.OrderDetails)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => pd.Book.Title)</td>
                    <td>@Html.DisplayFor(modelItem => pd.Book.Price)</td>
                    <td>@Html.DisplayFor(modelItem => pd.OrderQuantity)</td>
                    <td>@Html.DisplayFor(modelItem => pd.OrderExtendedPrice)</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <table class="table table-sm table-bordered" style="width:30%">
        <tr>
            <th colspan="2" style="text-align:center">Order Summary</th>
        </tr>
        <tr>
            <td>Order Subtotal</td>
            <td>@Html.DisplayFor(r => r.OrderSubtotal)</td>
        </tr>
        <tr>
            <td>Sales Tax (8.25%)</td>
            <td>@Html.DisplayFor(r => r.ShippingCost)</td>
        </tr>
        <tr>
            <td>Order Total</td>
            <td>@Html.DisplayFor(r => r.OrderTotal)</td>
        </tr>

    </table>
   
</div>

mrsProject/Views/Orders/OrderSummary.cshtml
@model mrsProject.Models.Order
@{
    ViewData["Title"] = "OrderSummary";
}

<h2>OrderConfirmation</h2>

<hr />

@using (Html.BeginForm())
{
    <div>


        <h6>Payment Method</h6> @Html.DisplayFor(model => model.PaymentMethod)

        <h4>Books</h4>
        <table class="table table-sm table-hover table-striped">
            <thead>
                <tr>
                    <th>Book Title</th>
                    <th>Book Price</th>
                    <th>Book Quantity</th>
                    <th>Book Extended Price</th>
                </tr>
            </thead>
            <tbody>
                @foreach (mrsProject.Models.OrderDetail pd in Model.OrderDetails)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => pd.Book.Title)</td>
                        <td>@Html.DisplayFor(modelItem => pd.Book.Price)</td>
                        <td>@Html.DisplayFor(modelItem => pd.OrderQuantity)</td>
                        <td>@Html.DisplayFor(modelItem => pd.OrderExtendedPrice)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div>
        <table class="table table-sm table-bordered" style="width:30%">
            <tr>
                <th colspan="2" style="text-align:center">Order Summary</th>
            </tr>
            <tr>
                <td>Order Subtotal</td>
                <td>@Html.DisplayFor(r => r.OrderSubtotal)</td>
            </tr>
            <tr>
                <td>Sales Tax (8.25%)</td>
                <td>@Html.DisplayFor(r => r.ShippingCost)</td>
            </tr>
            <tr>
                <td>Order Total</td>
                <td>@Html.DisplayFor(r => r.OrderTotal)</td>
            </tr>

        </table>

    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Place Order" class="btn btn-default">
        </div>
    </div>
}