mrsProject/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mrsProject.DAL;
using mrsProject.Models;
using mrsProject.Utilities;

namespace mrsProject.Controllers
{
    public class BooksController : Controller
    {
        private readonly AppDbContext _context;

        public BooksController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            return View(await _context.Books.ToListAsync());
        }

        // GET: Books
        public async Task<IActionResult> ReorderIndex()
        {
            return View(await _context.Books.ToListAsync());
        }


        // GET: Books/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null) //Repo id not specified
            {
                return View("Error", new String[] { "Book ID not specified - which book do you want to view?" });
            }

            Book b = _context.Books.Include(r => r.Genre).FirstOrDefault(r => r.BookID == id);

            if (b == null) //Repo does not exist in database
            {
                return View("Error", new String[] { "Book not found in database" });
            }

            //if code gets this far, all is well
            return View(b);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookID,BookUniqueID,Title,Author,ItemInStock,NumInStock,SimpleRating,LastOrderDate,ActiveStatus,Price,Cost,ReOrder,BookDescription,PublicationDate")] Book book)
        {
            book.BookUniqueID = GenerateNextUniqueNumber.GetNextUniqueNumber(_context);
            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
               
            }
            return View(book);
        }

        public async Task<IActionResult> ManualReorder(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManualReorder(int id, [Bind("BookID,BookUniqueID,Title,Author,ItemInStock,NumInStock,SimpleRating,LastOrderDate,ActiveStatus,Price,Cost,ReOrder,BookDescription,PublicationDate")] Book book)
        {
            //if (id != book.BookID)
            //{
                //return NotFound();
            //}
            
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.BookID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return View("Index", "Search");
            }
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookID,BookUniqueID,Title,Author,ItemInStock,NumInStock,SimpleRating,LastOrderDate,ActiveStatus,Price,Cost,ReOrder,BookDescription,PublicationDate")] Book book)
        {
            if (id != book.BookID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.BookID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.BookID == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Books.FindAsync(id);
            _context.Books.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Books.Any(e => e.BookID == id);
        }

       
    }
}

mrsProject/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mrsProject.DAL;
using mrsProject.Models;

namespace mrsProject.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly AppDbContext _context;

        public ReviewsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Reviews
        public IActionResult Index()
        {
            List<Review> Reviews = new List<Review>();

            if (User.IsInRole("Customer"))
            {
                Reviews = _context.Reviews.Include(o => o.Author).Where(o => o.Author.UserName == User.Identity.Name).ToList();
            }
            else
            {
                Reviews = _context.Reviews.Include(r => r.Author).Where(r => r.Pending == true).ToList();
            }
            return View(Reviews);

            
        }

        // GET: Reviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Reviews
                .FirstOrDefaultAsync(m => m.ReviewID == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // GET: Reviews/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? id, [Bind("ReviewID,Rating,Approved,Pending,ReviewDescription")] Review review)
        {
            if (ModelState.IsValid)
            {
                List<Book> Books = new List<Book>();

                Books = _context.Books.ToList();

                review.book = Books.FirstOrDefault(r => r.BookID == id);

                String name = User.Identity.Name;
                AppUser CurrentUser = _context.Users.FirstOrDefault(u => u.UserName == name);
                review.Author = CurrentUser;

                _context.Add(review);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(review);
        }

        // GET: Reviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Reviews.FindAsync(id);
            if (review == null)
            {
                return NotFound();
            }
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReviewID,Approved,ReviewDescription")] Review review)
        {
            if (id != review.ReviewID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(review);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewExists(review.ReviewID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(review);
        }

        // GET: Reviews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Reviews
                .FirstOrDefaultAsync(m => m.ReviewID == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var review = await _context.Reviews.FindAsync(id);
            _context.Reviews.Remove(review);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReviewExists(int id)
        {
            return _context.Reviews.Any(e => e.ReviewID == id);
        }
    }
}

mrsProject/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mrsProject.DAL;
using mrsProject.Models;

namespace mrsProject.Controllers
{
    public enum SortOptions { Title, Author, NumberPurchased, New, Old, Rated}
   
    public class SearchController : Controller

    {
        private AppDbContext _db;
        public IActionResult Index()
        {
            return View();
        }

       

        public ActionResult Search()
        {
            ViewBag.AllBooks = GetAllBooks();
            return View("SearchResults");
        }



        public ActionResult DisplaySearchResults(string SearchGenre, string SearchTitle, string SearchAuthor, SortOptions sort)
        {
            ViewBag.BookCount = "The total number of books is" + _db.Books.Count();
            List<Book> SelectedBooks = new List<Book>();
            

            var query = from r in _db.Books
                        select r;
            if (SearchGenre != null && SearchGenre != "")
            {
                query = query.Where(r => r.Genre.GenreName.Contains(SearchGenre));
            }
            if (SearchTitle != null && SearchTitle != "")
            {
                query = query.Where(r => r.Title.Contains(SearchTitle));
            }
            if (SearchAuthor != null && SearchAuthor != "")
            {
                query = query.Where(r => r.Author.Contains(SearchAuthor));
            }

            SelectedBooks = query.Include(r => r.Genre).ToList();
            ViewBag.TotalBooks = _db.Books.Count();
            ViewBag.SelectedBooks = SelectedBooks.Count();


            


            switch (sort)
            {
                case SortOptions.Title:
                    return View("SearchResults", SelectedBooks.OrderBy(r => r.Title));
                case SortOptions.Author:
                    return View("SearchResults", SelectedBooks.OrderBy(r => r.Author));
                case SortOptions.New:
                    return View("SearchResults", SelectedBooks.OrderBy(r => r.PublicationDate));
                case SortOptions.Old:
                    return View("SearchResults", SelectedBooks.OrderByDescending(r => r.PublicationDate));
                case SortOptions.NumberPurchased:
                    return View("SearchResults", SelectedBooks.OrderBy(r => r.NumPurchased));
                case SortOptions.Rated:
                    return View("SearchResults", SelectedBooks.OrderBy(r => r.SimpleRating));
            }
            

            return View();


        }

        public IActionResult BookDetails(int? id)
        {
            if (id == null) //Repo id not specified
            {
                return View("Error", new String[] { "Book ID not specified - which book do you want to view?" });
            }

            Book b = _db.Books.Include(r => r.Genre).FirstOrDefault(r => r.BookID == id);

            if (b == null) //Repo does not exist in database
            {
                return View("Error", new String[] { "Book not found in database" });
            }

            //if code gets this far, all is well
            return View(b);
        }

       
        public SearchController(AppDbContext context)
        {
            _db = context;
        }

        public SelectList GetAllBooks()
        {
            List<Book> Books = _db.Books.ToList();

            Book SelectNoBook = new Book() { BookID = 0, Title = "All Books" };

            Books.Add(SelectNoBook);

            SelectList AllBooks = new SelectList(Books.OrderBy(B => B.BookID), "BookID", "Title");

            return AllBooks;
        }

        public ActionResult AllBooks(string SearchString)
        {
            ViewBag.BookCount = "The total number of Books is " + _db.Books.Count();
            List<Book> SelectedBooks = new List<Book>();

            

            var query = from r in _db.Books
                        select r;

            SelectedBooks = query.Include(r => r.Genre).ToList();

            ViewBag.TotalBooks = _db.Books.Count();
            ViewBag.SelectedBooks = SelectedBooks.Count();
            return View("SearchResults", SelectedBooks);

        }
    }
}

mrsProject/Views/Search/BookDetails.cshtml
@model mrsProject.Models.Book
@{
    ViewData["Title"] = "BookDetails";
}

<h2>BookDetails</h2>

<div>
    
    
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BookUniqueID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BookUniqueID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SimpleRating)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SimpleRating)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Reviews)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Reviews)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PublicationDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PublicationDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre.GenreName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre.GenreName)
        </dd>


    </dl>
</div>
<div>
    <button type="submit" asp-controller="Search" asp-action="DisplaySearchResults" class="btn btn-secondary">Back to Search</button>
    <a asp-controller="Orders" asp-action="AddToOrder" asp-route-id="@Model.BookID">Add to Order</a> |
    <a asp-controller="Books" asp-action="ManualReorder" asp-route-id="@Model.BookID">Manual Reorder</a> |
    <a asp-controller="Reviews" asp-action="Create" asp-route-id="@Model.BookID">Add Review</a> |

</div>

mrsProject/Views/Search/Index.cshtml
@using mrsProject.Controllers
@model mrsProject.Models.Book
@{
    ViewData["Title"] = "Search";
}

<h2>Search</h2>

<form asp-action="Index" asp-controller="Search" method="get">
    <div class="form-group">
        <label>Genre:</label>
        <input name="SearchGenre" class="form-control" />
    </div>
    <div class="form-group">
        <label>Title:</label>
        <input name="SearchTitle" class="form-control" />
    </div>
    <div class="form-group">
        <label>Author:</label>
        <input name="SearchAuthor" class="form-control" />
    </div>

    <div class="form-group">
        <label>Select Sort</label>
        <label class="radio">@Html.RadioButton("sort", SortOptions.Title, true) Title</label>
        <label class="radio">@Html.RadioButton("sort", SortOptions.Author, true) Author</label>
        <label class="radio">@Html.RadioButton("sort", SortOptions.New, true) Newest</label>
        <label class="radio">@Html.RadioButton("sort", SortOptions.Old, true) Oldest</label>
        <label class="radio">@Html.RadioButton("sort", SortOptions.NumberPurchased, true) Most Popular</label>
        <label class="radio">@Html.RadioButton("sort", SortOptions.Rated, true) Highest Rated</label>
    </div>
    
    <p class="form-group">
        <button type="submit" asp-controller="Search" asp-action="DisplaySearchResults" class="btn btn-secondary">Search</button>
        <button type="submit" asp-controller="Search" asp-action="AllBooks" class="btn btn-secondary">Show All</button>
    </p>

</form>

mrsProject/Views/Search/SearchResults.cshtml
@model IEnumerable<mrsProject.Models.Book>


@{
    ViewData["Title"] = "SearchResults";
}

<h2>SearchResults</h2>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<p>
    Displaying @ViewBag.SelectedBooks out of @ViewBag.TotalBooks
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookUniqueID)
            </th>
            <td>
                @Html.DisplayNameFor(model => model.ItemInStock)
            </td>

            <th>
                @Html.DisplayNameFor(model => model.SimpleRating)
            </th>
                       
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BookUniqueID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemInStock)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SimpleRating)
                </td>
               
                <td>
                    <a asp-action="BookDetails" asp-route-id="@item.BookID">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>